/**
 * generate-config.js
 *
 * Reads Firebase credentials from .env (via firebase/firebaseConfig.js)
 * and writes them into public/firebase-config.js as a browser-safe
 * window.FIREBASE_CONFIG assignment.
 *
 * Run before serving:
 *   node scripts/generate-config.js
 *
 * Or automatically via npm scripts:
 *   npm start    →  generate-config + http-server
 *   npm run build →  generate-config only
 */

const path = require('path');
const fs   = require('fs');

// Load and validate config (exits on missing vars)
const config = require('../firebase/firebaseConfig');

const outDir  = path.join(__dirname, '..', 'public');
const outFile = path.join(outDir, 'firebase-config.js');

const content = `// Auto-generated by scripts/generate-config.js — DO NOT EDIT
// Source: .env → firebase/firebaseConfig.js → public/firebase-config.js
// Regenerate with: node scripts/generate-config.js

window.FIREBASE_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');

console.log('✅ public/firebase-config.js generado correctamente.');
console.log('   Project:', config.projectId);
console.log('   Auth domain:', config.authDomain);
